---
- hosts:
    - nfs_server
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5

  tasks:
    - name: "Create a ext4 filesystem on {{nfs_device}}"
      community.general.filesystem:
        fstype: ext4
        dev: "{{nfs_device}}"

    - name: "Ensure {{nfs_folder}} mounts exists"
      mount:
        src: "{{nfs_device}}"
        path: "{{nfs_folder}}"
        opts: rw,nosuid
        state: mounted
        fstype: ext4

    - include_role:
        name: geerlingguy.nfs
