---
kubernetes:
  children:
    master:
      hosts:
        talos0:
          ansible_host: talos0.mobile.cluster
        talos1:
          ansible_host: talos1.mobile.cluster
        talos2:
          ansible_host: talos2.mobile.cluster
linux:
  children:
    nfs_server:
      hosts:
        nfs:
          ansible_host: nfs.mobile.cluster
