apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml

patches:
  - target:
      kind: Namespace
      labelSelector: "app.kubernetes.io/name=kubelet-serving-cert-approver"
    patch: |-
      - op: remove
        path: /metadata/labels/pod-security.kubernetes.io~1audit
      - op: remove
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
      - op: remove
        path: /metadata/labels/pod-security.kubernetes.io~1warn
