apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UQ4CUzynPHQJZfR4Q7SjF6fxmm3LeWV2aDJen3QevFMUqXIL+1/SVg==,iv:LYuIswSOcZRty40U46W4WSG4VxNQlEnK+CX1+RL8rBY=,tag:N+rKaT9wwMghwhCR5QGD9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYmVlM0Z4MUpCcmpULzht
            alJ1RmFSMHEybHVRU1lFOEFsL3VHbC9UcnpzCnM0VHJobFhlODYvejZzVzhQazRQ
            bytiQ2VacVF4WjRiczFGZHBXbnJFb1UKLS0tIG5GbXY5cnZiVW45alBSZ3F5MmpX
            TUx6NFk1OVA5RUltUlBIeFNBbll1WlUK+hDt2DPyOAPrQsX/a//un4cADoH8nZAA
            gz0VfuBu0AEpe2lPZt0Mnq3q7ZWMvInofzVQId5sVl/dB3Gpp1n7NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T09:07:53Z"
    mac: ENC[AES256_GCM,data:NmtU+HI1/uWhhYL4Ixdp0EZMK5Iwaxt9BXHF4QulxbO7XrqJcuQSAXAuLhivuhkmWgtUzSpMGNw9DtpsWXufRleVIl0gCEFYqU7WNHAAKb8p3js8d9b7bB1CsIEP23ZZGdfzW+aWP4jlUS64BPnDAnGngO2AT/8u9p9QMBsXNA8=,iv:JJqCtzgaEwOGMBLp1X2c770kLyLXlgsr9pP+k30QvnU=,tag:Or/quENJXArveAH2oHJfpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
